required_tools:
  - subfinder
  - httpx
  - nuclei

optional_tools:
  - assetfinder
  - gau
  - waybackurls
  - gobuster
  - whatweb
  - unfurl
  - gf
  - uro
  - paramspider

tool_paths:
  nuclei_templates: /root/nuclei-templates
  wordlists_dir: /usr/share/wordlists

tools:
  subfinder:
    timeout: 300
    threads: 10
    silent: true
  httpx:
    timeout: 10
    threads: 50
    status_codes:
      - 200
      - 204
      - 301
      - 302
      - 401
      - 403
      - 405
      - 500
      - 502
      - 503
      - 504
  nuclei:
    concurrency: 25
    retries: 2
    rate_limit: 150
    timeout: 300
  gobuster:
    threads: 50
    timeout: 600
    extensions:
      - php
      - html
      - txt
      - js
  paramspider:
    exclude_extensions:
      - css
      - png
      - jpg
      - gif
      - svg
      - ico
      - woff
      - woff2
      - ttf
      - otf

wordlists:
  paths:
    - /usr/share/wordlists/seclists/Discovery/Web-Content/common.txt
    - /usr/share/wordlists/seclists/Discovery/Web-Content/directory-list-2.3-medium.txt
    - /usr/share/seclists/Discovery/Web-Content/common.txt
    - /usr/share/wordlists/dirb/common.txt
    - /usr/share/dirb/wordlists/common.txt